on:
  push:
    # this is the branch where you develop your site
    # as discussed in the publishing sources section
    # this can change if you are using an user/organization repo
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLIC_PATH: /nightbot-oauth2-app
    steps:
    - uses: actions/checkout@v2
    - name: Package
      run: |
        mkdir build
        tar -cvzf build/twitch-cp-title.op ./*.as ./*.toml
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        branch: archives